import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Header,RecentOrders,TopCard,BarChart } from '../components'


const inter = Inter({ subsets: ['latin'] })





export default function Home() {
  return (
    <>
      <Head>
        <title>dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className=''>
        <section className=''>
          <Header/>
          <TopCard/>
          <div className='block md:flex items-center gap-10 p-5'>
            <BarChart/>
            <RecentOrders/>
          </div>
        </section>
      </main>
    </>
  )
}
